version: "3.8"

services:
  back:
    container_name: $BACK_CONTAINER_NAME
    build:
      context: ./back
      dockerfile: Dockerfile.back
      args:
        - BACK_PORT=$BACK_PORT
    ports:
      - $BACK_PORT:$BACK_PORT
    env_file: .env

  front:
    container_name: $FRONT_CONTAINER_NAME
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
      args:
        - FRONT_PORT=$FRONT_PORT
    ports:
      - $FRONT_PORT:$FRONT_PORT
      - 443:443
    env_file: .env
    volumes:
      - ./$FRONT_SSL_PATH:/etc/nginx/ssl:ro

  astronode:
    container_name: $FRONT_ASTRONODE_CONTAINER_NAME
    build:
      context: ./front
      dockerfile: Dockerfile.front
      args:
        - FRONT_ASTRONODE_PORT=$FRONT_ASTRONODE_PORT
    ports:
      - $FRONT_ASTRONODE_PORT:$FRONT_ASTRONODE_PORT
    env_file: .env
