version: "3.8"

services:
  back:
    container_name: $BACK_CONTAINER_NAME
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        - BACK_PORT=$BACK_PORT
    ports:
      - $BACK_PORT:$BACK_PORT
    env_file: .env

  front:
    container_name: $FRONT_CONTAINER_NAME
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - FRONT_PORT=$FRONT_PORT
    ports:
      - $FRONT_PORT:$FRONT_PORT
    env_file: .env
    volumes:
      - ./$FRONT_SSL_PATH:/etc/nginx/ssl:ro
