name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          SSH_USER_NAME: ${{ secrets.SSH_USER_NAME}}
          SSH_HOST_IP: ${{ secrets.SSH_HOST_IP}}
          SSH_PORT: ${{ secrets.SSH_PORT}}
          REPOSITORY_PATH: ${{ secrets.REPOSITORY_PATH }}
          DOCKER_STOP_SCRIPT: ${{ secrets.DOCKER_STOP_SCRIPT }}
          DOCKER_START_SCRIPT: ${{ secrets.DOCKER_START_SCRIPT }}
        run: |
          mkdir -p .ssh chmod 700 .ssh
          echo "$SSH_PRIVATE_KEY" > .ssh/private_key
          chmod 600 .ssh/private_key
          ssh -tt -o StrictHostKeyChecking=no -i .ssh/private_key ${SSH_USER_NAME}@${SSH_HOST_IP} -p ${SSH_PORT} "
            cd ${REPOSITORY_PATH}
            sh ${DOCKER_STOP_SCRIPT}
            git fetch origin main
            git reset origin/main
            git restore .
            sh ${DOCKER_START_SCRIPT}
          exit
          "
