name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo pacman -Syyu --noconfirm
            cd ${{ secrets.REPOSITORY_PATH }}
            sh ${{ secrets.DOCKER_STOP_SCRIPT }}
            cd
            rm -fr ${{ secrets.REPOSITORY_PATH }}
            git clone ${{ secrets.REPOSITORY_URL }} ${{ secrets.REPOSITORY_PATH }}
            cd ${{ secrets.REPOSITORY_PATH }}
            echo "${{ secrets.ENV_FILE }}" > .env
            mkdir -p  ${{ secrets.SSL_PATH }}
            echo "${{ secrets.SSL_CRT }}" > ${{ secrets.SSL_PATH }}/${{ secrets.SSL_CRT_FILE_NAME }}
            echo "${{ secrets.SSL_PRIVATE_KEY }}" > ${{ secrets.SSL_PATH }}/${{ secrets.SSL_PRIVATE_KEY_FILE_NAME }}
            sh ${{ secrets.DOCKER_START_SCRIPT }}
