name: golangci-lint

on:
  pull_request:
  push:
    branches:
      - "main"
      - "master"

env:
  GO_VERSION: 1.24.x
  GOLANGCI_LINT_VERSION: v2.0

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: back
