name: Health check

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check website availability
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://yanosea.org
          max-attempts: 3
          retry-delay: 5s
