name: Backend Quality Check

on:
  pull_request:
    branches: [main]

env:
  DENO_VERSION: "2.x"

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Quality checks
        run: make back.check

      - name: Test
        run: make back.test
